# see http://www.martyndavis.com/?p=335 for required hack on Ubuntu Precise
# see http://mjo.tc/atelier/2009/02/arduino-cli.html

ARDUINO_DIR = /usr/share/arduino
BOARD_TAG    = nano328
ARDUINO_PORT = /dev/ttyUSB* /dev/ttyACM*
ARDUINO_LIBS = SPI EEPROM UDEV
include /usr/share/arduino/Arduino.mk
